[package]
name = "llama-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
ggml-raw = { path = "../ggml-raw" }
partial_sort = "0.2.0"
thiserror = "1.0"

rand = { workspace = true }
serde = { version = "1.0.156", features = ["derive"] }
bincode = "1.3.3"

tokenizers = { git = "https://github.com/huggingface/tokenizers", rev = "5ecd329503a4ac137bf00442ede4d31140276eb1" }
